version: "2"
services:
  web:
    build: .
    volumes:
      - ../frontend:/src/public
    ports:
      - "8084:3000"
  mongo:
    image: mongo
    volumes:
      - ../../WTDatabase:/data/db
    expose:
      - "27017"
